on: ["push", "pull_request"]

name: Test Coveralls

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Run Coveralls
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          pip install -r tests/test_requirements.txt --use-mirrors
          py.test tests/test_processing.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
          coveralls --service=github
