on: ["push", "pull_request"]

name: Coverage Test

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8","3.9","3.10","3.11"]
    steps:

    - uses: actions/checkout@v1

    - name: Install coverage test packages
      run: |
          pip install -r tests/test_requirements.txt
          pip3 install --upgrade coveralls
                    
    - name: Install main packages
      run: |
          pip install -r requirements.txt
          
    - name: Run Coveralls
      run: |
          py.test tests/ --doctest-modules -v --cov ampy --cov-report term-missing
          coveralls --service=gihtub
